---
# vars file for deploy_k3s

deploy_longhorn_open_iscsi_ver : 2.1.9-3ubuntu5.4
deploy_longhorn_nfs_common_ver : 1:2.6.4-3ubuntu5.1
deploy_k3s_k3s_version         : v1.35.0+k3s3
deploy_k3s_cluster_token       : FDiA$pHlSgSv8KyX6FP906OIZa#m@Y
deploy_k3s_flannel_backend     : wireguard-native
deploy_k3s_cluster_cidr        : 172.16.0.0/16
deploy_k3s_service_cidr        : 172.17.0.0/16
deploy_k3s_cluster_dns         : 172.17.0.10
deploy_k3s_tls_san             : k3s.local
deploy_k3s_cluster_domain      : k3s.local
deploy_k3s_bootstrap_master_ip : 10.10.5.191