---
# tasks file for deploy_web_debugger

- name: create a directory {{ deploy_web_debugger_project_src }}
  ansible.builtin.file:
    path: "{{ deploy_web_debugger_project_src }}"
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: template a file {{ deploy_web_debugger_project_src }}/docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ deploy_web_debugger_project_src }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart_web_debugger

- name: create and start web_debugger version={{ deploy_web_debugger_image_version }}
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_web_debugger_project_src }}"
    state: present
