---
# tasks file for deploy_mariadb_galera

- name: create a directory {{ deploy_mariadb_galera_project_src }}
  ansible.builtin.file:
    path: "{{ deploy_mariadb_galera_project_src }}"
    state: directory
    mode: '0777'
    owner: root
    group: root

- name: create a directory {{ deploy_mariadb_galera_project_src }}/data
  ansible.builtin.file:
    path: "{{ deploy_mariadb_galera_project_src }}/data"
    state: directory
    mode: '0777'
    owner: root
    group: root

- name: create a directory {{ deploy_mariadb_galera_project_src }}/mariadb.conf.d
  ansible.builtin.file:
    path: "{{ deploy_mariadb_galera_project_src }}/mariadb.conf.d"
    state: directory
    mode: '0777'
    owner: root
    group: root

- name: template a file {{ deploy_mariadb_galera_project_src }}/mariadb.cnf
  ansible.builtin.template:
    src: mariadb.cnf.j2
    dest: "{{ deploy_mariadb_galera_project_src }}/mariadb.cnf"
    owner: root
    group: root
    mode: '0444'
    backup: true
#  notify: restart_mariadb_galera

- name: template a file {{ deploy_mariadb_galera_project_src }}/mariadb.conf.d/60-galera.cnf
  ansible.builtin.template:
    src: 60-galera.cnf.j2
    dest: "{{ deploy_mariadb_galera_project_src }}/mariadb.conf.d/60-galera.cnf"
    owner: root
    group: root
    mode: '0444'
    backup: true
#  notify: restart_mariadb_galera

- name: template a file {{ deploy_mariadb_galera_project_src }}/docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ deploy_mariadb_galera_project_src }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'
    backup: true
#  notify: restart_mariadb_galera

- name: create and start mariadb_galera version={{ deploy_mariadb_galera_image_version }}
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_mariadb_galera_project_src }}"
    state: present