#SPDX-License-Identifier: MIT-0
---
# handlers file for deploy_consul_server

- name: restart_consul_server
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_consul_server_project_src }}"
    state: restarted

- name: reload_consul_server
  community.docker.docker_container_exec:
    container: consul-server
    command: consul reload