---
# tasks file for deploy_angie_reverse_proxy

- name: create a directory {{ deploy_angie_project_src }}
  ansible.builtin.file:
    path: "{{ deploy_angie_project_src }}"
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: create a directory {{ deploy_angie_project_src }}/http.d
  ansible.builtin.file:
    path: "{{ deploy_angie_project_src }}/http.d"
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: create a directory /var/log/angie
  ansible.builtin.file:
    path: "/var/log/angie"
    state: directory
    mode: '0777'
    owner: root
    group: root

- name: copy a file {{ deploy_angie_project_src }}/angie.conf
  ansible.builtin.copy:
    src: angie.conf
    dest: "{{ deploy_angie_project_src }}/angie.conf"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: reload_angie

- name: copy a files {{ deploy_angie_project_src }}/http.d/
  ansible.builtin.template:
    src: http.d/backend.conf.j2
    dest: "{{ deploy_angie_project_src }}/http.d/backend.conf"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: reload_angie

- name: template a file {{ deploy_angie_project_src }}/docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ deploy_angie_project_src }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart_angie

- name: create and start angie version={{ deploy_angie_image_version }}
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_angie_project_src }}"
    state: present
