deploy_keepalived_router_id       : lb02
deploy_keepalived_state           : BACKUP
deploy_keepalived_priority        : 100
deploy_keepalived_unicast_src_ip  : 10.10.5.112
deploy_keepalived_unicast_peer    : 10.10.5.111
deploy_keepalived_vrrp_interface  : eth0