filebeat.inputs:
- type: log
  id: log
  enabled: true
  paths:
    - /var/log/*.log
    - /var/log/nginx/*.log
  fields:
    application: log
  fields_under_root: true
  exclude_files: ['.gz$']
  prospector.scanner.exclude_files: ['.gz$']

- type: log
  id: container
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log
  fields:
    application: container
  fields_under_root: true
  exclude_files: ['.gz$']
  prospector.scanner.exclude_files: ['.gz$']

output.kafka:
  enabled: true
  hosts: ["10.10.5.181:9092", "10.10.5.182:9092", "10.10.5.183:9092",]
  topic: '%{[application]}'