---
# tasks file for deploy_consul_server

- name: create a directory {{ deploy_consul_server_project_src }}
  ansible.builtin.file:
    path: "{{ deploy_consul_server_project_src }}"
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: create a directory {{ deploy_consul_server_project_src }}/data
  ansible.builtin.file:
    path: "{{ deploy_consul_server_project_src }}/data"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: template a file {{ deploy_consul_server_project_src }}/docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ deploy_consul_server_project_src }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart_consul_server

- name: template a file {{ deploy_consul_server_project_src }}/config.json
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ deploy_consul_server_project_src }}/config.json"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: reload_consul_server

- name: create and start consul_server version={{ deploy_consul_server_image_version }}
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_consul_server_project_src }}"
    state: present